using ModelContextProtocol.Protocol;
using System.Text.Json;
using System.Collections.Generic;

namespace RunalyzeMcp
{
    public static class ToolDefinitions
    {
        public static readonly List<Tool> AllTools = new List<Tool>
        {
            new Tool { Name = "api_activity_upload", Description = "Upload an activity file to Runalyze",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""file"":{""type"":""string"",""description"":""Activity file as base64-encoded string""},""filename"":{""type"":""string"",""description"":""Filename of the activity file""}},""required"":[""file"",""filename""]}") },
            new Tool { Name = "api_activity_download", Description = "Download an activity file from Runalyze",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID to download""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activitiesuploads_id_get", Description = "Get upload status for an activity",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Upload ID to check""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activities_id_get", Description = "Get activity details",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activities_get", Description = "Get list of activities from Runalyze",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""limit"":{""type"":""integer"",""description"":""Number of activities to return""},""offset"":{""type"":""integer"",""description"":""Number of activities to skip""}},""required"":[]}") },
            new Tool { Name = "api_v1activity_id_fit_get", Description = "Download original FIT file",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activity_id_fitlog_get", Description = "Download FITLOG file",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activity_id_gpx_get", Description = "Download GPX file",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activity_id_kml_get", Description = "Download KML file",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activity_id_social_image_get", Description = "Download social image",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1activity_id_tcx_get", Description = "Download TCX file",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer"",""description"":""Activity ID""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1statistics_get", Description = "Get user statistics from Runalyze",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{},""required"":[]}") },
            new Tool { Name = "api_v1equipment_get", Description = "Get user equipment",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1equipment_id_get", Description = "Get specific equipment",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1equipment_category_get", Description = "Get equipment categories",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1equipment_category_id_get", Description = "Get specific equipment category",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1health_bulk_upload_post", Description = "Bulk upload health data",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""file"":{""type"":""string"",""description"":""Health data file as base64-encoded string""}},""required"":[""file""]}") },
            new Tool { Name = "api_v1metrics_blood_glucose_get", Description = "Get blood glucose metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_blood_glucose_post", Description = "Create blood glucose metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_blood_glucose_id_get", Description = "Get blood glucose metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1metrics_blood_pressure_get", Description = "Get blood pressure metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_blood_pressure_post", Description = "Create blood pressure metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_blood_pressure_id_get", Description = "Get blood pressure metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1metrics_body_composition_get", Description = "Get body composition metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_body_composition_post", Description = "Create body composition metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_body_composition_id_get", Description = "Get body composition metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1metrics_body_temperature_get", Description = "Get body temperature metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_body_temperature_post", Description = "Create body temperature metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_body_temperature_id_get", Description = "Get body temperature metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1metrics_daily_note_get", Description = "Get daily note metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_daily_note_post", Description = "Create daily note metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_daily_note_date_get", Description = "Get daily note by date",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""date"":{""type"":""string"",""description"":""Date in YYYY-MM-DD format""}},""required"":[""date""]}") },
            new Tool { Name = "api_v1metrics_hrv_get", Description = "Get HRV metrics from Runalyze",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_hrv_post", Description = "Create HRV metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_hrv_id_get", Description = "Get HRV metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1metrics_heart_rate_max_get", Description = "Get heart rate max metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_heart_rate_max_post", Description = "Create heart rate max metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_heart_rate_max_id_get", Description = "Get heart rate max metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1metrics_heart_rate_rest_get", Description = "Get resting heart rate metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_heart_rate_rest_post", Description = "Create resting heart rate metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_heart_rate_rest_id_get", Description = "Get resting heart rate metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1metrics_mental_get", Description = "Get mental metrics",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_mental_post", Description = "Create mental metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_mental_date_get", Description = "Get mental metric by date",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""date"":{""type"":""string""}},""required"":[""date""]}") },
            new Tool { Name = "api_v1metrics_sleep_get", Description = "Get sleep metrics from Runalyze",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1metrics_sleep_post", Description = "Create sleep metric",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""metricData"":{""type"":""object""}},""required"":[""metricData""]}") },
            new Tool { Name = "api_v1metrics_sleep_id_get", Description = "Get sleep metric by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
            new Tool { Name = "api_v1raceresults_get", Description = "Get user race results",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1raceresults_activity_id_get", Description = "Get race result by activity",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""activityId"":{""type"":""integer""}},""required"":[""activityId""]}") },
            new Tool { Name = "api_v1tags_get", Description = "Get user tags",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""page"":{""type"":""integer""},""orderById"":{""type"":""string""}},""required"":[]}") },
            new Tool { Name = "api_v1tags_id_get", Description = "Get tag by ID",
                InputSchema = JsonSerializer.Deserialize<JsonElement>(@"{""type"":""object"",""properties"":{""id"":{""type"":""integer""}},""required"":[""id""]}") },
        };
    }
}
